vim.keymap.set('n', '<Leader>1', '<Cmd>BufferLineGoToBuffer 1<CR>')
vim.keymap.set('n', '<Leader>2', '<Cmd>BufferLineGoToBuffer 2<CR>')
vim.keymap.set('n', '<Leader>3', '<Cmd>BufferLineGoToBuffer 3<CR>')
vim.keymap.set('n', '<Leader>4', '<Cmd>BufferLineGoToBuffer 4<CR>')
vim.keymap.set('n', '<Leader>5', '<Cmd>BufferLineGoToBuffer 5<CR>')
vim.keymap.set('n', '<Leader>6', '<Cmd>BufferLineGoToBuffer 7<CR>')
vim.keymap.set('n', '<Leader>7', '<Cmd>BufferLineGoToBuffer 7<CR>')
vim.keymap.set('n', '<Leader>8', '<Cmd>BufferLineGoToBuffer 8<CR>')
vim.keymap.set('n', '<Leader>9', '<Cmd>BufferLineGoToBuffer 9<CR>')

vim.keymap.set('n', '<Leader>sl', ':rightbelow vsplit<CR>', { desc = 'Vertical split right' })
vim.keymap.set('n', '<Leader>sh', ':leftabove vsplit<CR>', { desc = 'Vertical split left' })
vim.keymap.set('n', '<Leader>sj', ':rightbelow split<CR>', { desc = 'Horizontal split below' })
vim.keymap.set('n', '<Leader>sk', ':leftabove split<CR>', { desc = 'Horizontal split above' })
