# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@tauri-apps/api-2.5.0" = {
      name = "_at_tauri-apps_slash_api";
      packageName = "@tauri-apps/api";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tauri-apps/api/-/api-2.5.0.tgz";
        sha512 = "Ldux4ip+HGAcPUmuLT8EIkk6yafl5vK0P0c0byzAKzxJh7vxelVtdPONjfgTm96PbN24yjZNESY8CKo8qniluA==";
      };
    };
    "@tauri-apps/plugin-opener-2.2.6" = {
      name = "_at_tauri-apps_slash_plugin-opener";
      packageName = "@tauri-apps/plugin-opener";
      version = "2.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tauri-apps/plugin-opener/-/plugin-opener-2.2.6.tgz";
        sha512 = "bSdkuP71ZQRepPOn8BOEdBKYJQvl6+jb160QtJX/i2H9BF6ZySY/kYljh76N2Ne5fJMQRge7rlKoStYQY5Jq1w==";
      };
    };
    "csstype-3.1.3" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.3.tgz";
        sha512 = "M1uQkMl8rQK/szD0LNhtqxIPLpimGm8sOBwU7lLnCpSbTyY3yeU1Vc7l4KT5zT4s/yOxHH5O7tIuuLOCnLADRw==";
      };
    };
    "seroval-1.3.0" = {
      name = "seroval";
      packageName = "seroval";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/seroval/-/seroval-1.3.0.tgz";
        sha512 = "4tYQDy3HVM0JjJ1CfDK3K8FhBKIDDri27oc2AyabuuHfQw6/yTDPp2Abt1h2cNtf1R0T+7AQYAzPhUgqXztaXw==";
      };
    };
    "seroval-plugins-1.3.0" = {
      name = "seroval-plugins";
      packageName = "seroval-plugins";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/seroval-plugins/-/seroval-plugins-1.3.0.tgz";
        sha512 = "FFu/UE3uA8L1vj0CXXZo2Nlh10MtYoOs0G//ptwlQMjfPFSeIVYUNy0zewfV8iM0CrOebAfHEG6J3xA9c+lsaQ==";
      };
    };
    "solid-js-1.9.6" = {
      name = "solid-js";
      packageName = "solid-js";
      version = "1.9.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/solid-js/-/solid-js-1.9.6.tgz";
        sha512 = "PoasAJvLk60hRtOTe9ulvALOdLjjqxuxcGZRolBQqxOnXrBXHGzqMT4ijNhGsDAYdOgEa8ZYaAE94PSldrFSkA==";
      };
    };
  };
  args = {
    name = "greeter";
    packageName = "greeter";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."@tauri-apps/api-2.5.0"
      sources."@tauri-apps/plugin-opener-2.2.6"
      sources."csstype-3.1.3"
      sources."seroval-1.3.0"
      sources."seroval-plugins-1.3.0"
      sources."solid-js-1.9.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
